In [1]:
# Introduction to numpy=>
# numpy is an open-source library that is used for scintific calculations.

In [2]:
# How numpy is better than list?
# 1.numpy is homogeneous data type while list hetrogenous data type.
# 2.numpy takes less memory while list take more memory.
# 3.numpy take less execution time while list take more execution.

In [34]:
import numpy as np

In [11]:
a=[1,24,34,45,90]
type(a)
b=np.array(a)
b

array([ 1, 24, 34, 45, 90])

In [12]:
a=[]
size=int(input("enter the size"))
for i in range(size):
    val=int(input("enter the element"))
    a.append(val)
print(a)
b=np.array(a)
b

enter the size 2
enter the element 10
enter the element 20


[10, 20]


array([10, 20])

In [35]:
type(b)

numpy.ndarray

In [39]:
a=[[1,2,3,4],[4,5,6,7],[7,8,9,5]]
a

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 5]]

In [36]:
b=np.array(a)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
print("Total rows and columns:",b.shape)  #shape for n(rows),n(column)
print("total element:",b.size)  #size=total element=n(rows) * n(column)
print("total dimension:",b.ndim) #ndim stand for n_dimensional.

Total rows and columns: (3, 4)
total element: 12
total dimension: 2


In [22]:
# Function in Numpy=>
# 1.zeros()--->it will be create an array in which all
# the values either one dimensional or multi-dimensional will be 0.
a=np.zeros(3)
a

array([0., 0., 0.])

In [23]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# 2.ones-->it will bw create an array in which all the values will be 1 in either one dimensional
# or multi-dimensional.
a=np.ones(3)
a

array([1., 1., 1.])

In [27]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
# 3. eyes()--->
# matrix-->digonal position--->1
# It will be create an array in which digonal positional element will be 1 and rest all are 0.

In [30]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [40]:
# 4.diag()-->It will be create an array in which you can set custom values at digonal position .

In [42]:
a=np.diag([1,45,78,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [43]:
# 5. Random()---->It will return random numbers.


In [44]:
# (a).Randint()--->It will return random number in a given.
# syntax-->
# np.random.randint(min_number,max_number,tital_numbers)

In [45]:
a=np.random.randint(1,10,3)
a

array([5, 9, 9])

In [46]:
# (b).rand()--->It will provide random number in range of 0 to 1.

In [47]:
a=np.random.rand(4)
a

array([0.90906645, 0.10476116, 0.94437022, 0.73345528])

In [48]:
# Random Numbers---->data use --->output
# if random number refresh update---->previous output change.

In [50]:
# (c).seed()--->It will fix our randon genrated data.
np.random.seed(10)
a=np.random.randint(1,10,3)
a

array([5, 1, 2])

In [51]:
# View vs Copy==>
# view means modification in original data and copy means modification data

In [52]:
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
b=a[3:6]
b[:]=0
b

array([0, 0, 0])

In [55]:
a

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [59]:
a=np.array([10,20,30,40,50,60,70,80,90])
b=a[3:6].copy()
b[:]=0
b

array([0, 0, 0])

In [60]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])