In [3]:
import numpy as np
# operation in array-->
a=np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [5]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [6]:
a[a%2==0]
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
a[a%2!=0]
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [9]:
# Reshaping the array==>
# n(row)*n(column)=toten_element

In [10]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
a.shape

(12,)

In [12]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [13]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
a.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [16]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [17]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [18]:
a+b

array([[ 6,  8],
       [10, 12]])

In [19]:
a-b

array([[-4, -4],
       [-4, -4]])

In [20]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [21]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [22]:
a**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [25]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [26]:
a

array([[1, 2],
       [3, 4]])

In [28]:
# linspace()---->It will return same gap values in a give range.
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [30]:
# unique-->It will prove array in which it will return 3 array.
# arr--->return unique value.
# return_index=True---->retun indexing value .
# return_count=True---->return frequency of each element.
a=np.array([1,55,5,5,1,1,55])
a

array([ 1, 55,  5,  5,  1,  1, 55])

In [32]:
np.unique(a,return_index=True,return_counts=True)

(array([ 1,  5, 55]),
 array([0, 2, 1], dtype=int64),
 array([3, 2, 2], dtype=int64))

In [33]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.sum(a)

45

In [35]:
np.sum(a,axis=0)

array([12, 15, 18])

In [36]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [38]:
# hstack and vstack---->
a=np.arange(1,5)
b=np.arange(5,9)
c=np.arange(9,13)
np.hstack(())